/**
 * Tailwind Configuration File
 * ==========================================================================
 * Purpose:
 * Defines the design tokens (colors, typography, spacing) and build settings
 * for the Tailwind CSS framework used in this theme.
 *
 * Core Logic:
 * 1. Content Scanning: Tells Tailwind where to look for class names (TSX/TS files).
 * 2. Theme Extension: Defines custom colors, fonts, and spacing values.
 * 3. Dark Mode: Configured via class strategy to support .dark class toggling.
 *
 * Architecture Role:
 * This file is the "Brain" of the visual design system. It ensures that
 * utility classes generated by Tailwind match the project's design specs.
 *
 * Color System (工业铜材 B2B 品牌三色):
 * - Primary Blue   #0B3570  — 工业海军蓝，用于导航、标题、主要按钮
 * - Action Copper  #F97C30  — 铜橙，用于 CTA 按钮、高亮标签、行动引导
 * - Accent Gold    #F4BD5D  — 工业金，用于图标点缀、徽章、次级强调
 *
 * Critical Notes:
 * - This project uses Tailwind CSS v4 (CSS-first config via globals.css).
 * - This file serves as a design documentation reference and for external
 *   tooling that requires a tailwind.config.js (e.g., IDE IntelliSense).
 * - The authoritative token source is `app/globals.css` (@theme inline block).
 * ==========================================================================
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  // 1. Content Scanning (扫描路径)
  // 告诉 Tailwind 在哪里寻找类名，涵盖所有 TSX/TS/JS 文件。
  content: [
    "./blocks/**/*.php",
    "./inc/**/*.php",
    "./templates/**/*.php",
    "./template-parts/**/*.php",
    "./functions.php",
    "./*.php",
  ],

  safelist: [
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-3",
    "grid-cols-4",
  ],

  // 2. Dark Mode Strategy (暗色模式策略)
  // 使用 class 策略，通过在 <html> 上添加 .dark 类切换暗色主题。
 
  darkMode: "class",

  // 3. Theme Extension (主题扩展)
  theme: {
    extend: {
      // --- I. Color System (颜色系统) ---
      // 对应 app/globals.css 中的 CSS 变量定义。
      colors: {
        // 品牌主色
        "primary-blue": "#0B3570",   // 工业海军蓝 — 导航、标题、主按钮
        "action-copper": "#F97C30",  // 铜橙 — CTA 按钮、高亮标签
        "accent-gold": "#F4BD5D",    // 工业金 — 图标点缀、徽章

        // 语义化颜色 (映射 CSS 变量)
        primary: {
          DEFAULT: "#0B3570",
          foreground: "#FFFFFF",
        },
        secondary: {
          DEFAULT: "#F97C30",
          foreground: "#FFFFFF",
        },
        accent: {
          DEFAULT: "#F4BD5D",
          light: "#FEF0C7", // 增加浅色变体，用于表格行悬停 (Status Anchors)
          foreground: "#1F2937",
        },

        // 文本色阶
        heading: "#1F2937",   // 主标题
        body: "#6B7280",      // 正文
        muted: "#9CA3AF",     // 弱化文本

        // 背景色阶
        bg: {
          page: "#FFFFFF",
          section: "#F2F4F7",
          dark: "#1A1A1A",
        },

        // 边框色
        border: {
          DEFAULT: "#E5E7EB",
          strong: "#D1D5DB",
        },

        // 状态色
        destructive: {
          DEFAULT: "#DC2626",
          foreground: "#FFFFFF",
        },
      },

      // --- II. Typography (排版) ---
      fontFamily: {
        // 对应 globals.css @theme inline 中的 --font-sans / --font-mono
        // 修正为设计系统要求的 Geist 和 Geist Mono
        // 注意: CDN 加载的 font-family 为 'Geist Sans' 和 'Geist Mono'
        sans: ["Geist Sans", "Geist", "system-ui", "-apple-system", "sans-serif"],
        mono: ["Geist Mono", "Geist Mono Fallback", "monospace"], // 用于技术参数、规格表
      },

      // --- III. Layout & Spacing (布局与间距) ---
      maxWidth: {
        // 内容区最大宽度，背景全宽，内容居中约束
        container: "1280px",
        "container-sm": "960px",
      },
      padding: {
        container: "24px",           // 容器水平内边距
        "section-y": "96px",         // 标准区块垂直间距
        "section-y-sm": "64px",      // 小区块垂直间距
        card: "32px",                // 卡片内边距
      },

      // --- IV. Border Radius (圆角) ---
      // 对应 globals.css 中 --radius: 0.25rem (偏方正的工业风格)
      // 严格遵循微圆角设计哲学：2px (sm) / 4px (default)
      borderRadius: {
        card: "4px",    // 卡片圆角 (从 8px 调整为 4px，符合工业硬朗感)
        button: "4px",  // 按钮圆角 (方正风格)
        tag: "2px",     // 标签/徽章圆角
        input: "2px",   // 输入框圆角
      },

      // --- V. Box Shadow (阴影) ---
      boxShadow: {
        card: "0 2px 12px rgba(11, 53, 112, 0.08)",       // 卡片投影（主色调）
        "card-hover": "0 8px 24px rgba(11, 53, 112, 0.16)", // 卡片悬停投影
        button: "0 2px 6px rgba(249, 124, 48, 0.30)",     // 铜橙按钮投影
      },

      // --- VI. Letter Spacing (字间距) ---
      letterSpacing: {
        tag: "0.08em",     // 标签/徽章大写字间距
        heading: "-0.01em", // 大号标题微收紧
      },
    },
  },

  plugins: [],
};
